const loggedInUser = {
  id: 1,
  firstName   : 'Anderson',
  lastName    : 'Khorsandi',
  description : 'Expert in mowing grass hills.',
  email       : 'Anderson.Khorsandi@gmail.com',
  password    : 'alligator',
  phone       : '(636)313-2463',
  addressId   : 1,
  stars       : 2,
  avatar      : 'https://xsgames.co/randomusers/assets/avatars/male/34.jpg',
  skills      : 'Yardwork and moving stuff.',
  address: {
    id        : 1,
    address   : '305 Wychwood Ave',
    city      : 'York',
    postcode  : 'M6C 2T6',
    latitude  : '43.68739440726955',
    longitude : '-79.42498784917888'
  }
};

const allUsers = [
  {
    id: 1,
    firstName: 'Anderson',
    lastName: 'Khorsandi',
    description: 'Expert in mowing grass hills.',
    email: 'Anderson.Khorsandi@gmail.com',
    password: 'alligator',
    phone: '(636)313-2463',
    addressId: 1,
    stars: 2,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/34.jpg',
    skills: 'Yardwork and moving stuff.'
  },
  {
    id: 2,
    firstName: 'Kayleen',
    lastName: 'Lunski',
    description: 'Ex-Formula 1 driver, great at helping people get to places on time.',
    email: 'K.Lunski@ferrari.it',
    password: 'aardvark',
    phone: '(416)500-1413',
    addressId: 2,
    stars: 1,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/7.jpg',
    skills: 'Safe driver and pretty good baker.'
  },
  {
    id: 3,
    firstName: 'Tiana',
    lastName: 'Wahman',
    description: 'Super Chef! Ready to help if you need help with meals or some cookies for your fundraiser.',
    email: 'TianaW@ovengloves.com',
    password: 'burntthetoast',
    phone: '(866)987-6453',
    addressId: 3,
    stars: 2,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/27.jpg',
    skills: 'Incredible in the kitchen.'
  },
  {
    id: 4,
    firstName: 'Elvis',
    lastName: 'Jarzynka',
    description: 'Friendly carpenter... if you need any shelves putting up?!',
    email: 'elvis@graceland.com',
    password: 'funnydancer',
    phone: '(514)347-3653',
    addressId: 4,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/27.jpg',
    skills: 'Woodwork and general DIY tasks.'
  },
  {
    id: 5,
    firstName: 'Javier',
    lastName: 'Tarczynski',
    description: 'Wonderful singer if you need a little cheering up, can also move heavy furniture.',
    email: 'jtarc2010@karaoke.com',
    password: 'sofaman',
    phone: '(306)551-8238',
    addressId: 5,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/21.jpg',
    skills: 'Dancing.'
  },
  {
    id: 6,
    firstName: 'Lore',
    lastName: 'Winks',
    description: 'Great with animals if your dog ever needs a walk.',
    email: 'l.winks2010@nature.com',
    password: 'gooddog',
    phone: '(905)725-6089',
    addressId: 6,
    stars: 2,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/21.jpg',
    skills: 'Animal care'
  },
  {
    id: 7,
    firstName: 'Miriam',
    lastName: 'Bohannes',
    description: 'I love baking sweets, and walking dogs!',
    email: 'miriam@bakesale.ca',
    password: 'cupcake',
    phone: '(416)313-2463',
    addressId: 7,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/19.jpg',
    skills: 'Baking.'
  },
  {
    id: 8,
    firstName: 'Marcella',
    lastName: 'DiPiaggo',
    description: 'Good with computers.',
    email: 'M.DiPiaggo@newegg.ca',
    password: 'floppyD',
    phone: '(416)313-2443',
    addressId: 8,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/17.jpg',
    skills: 'Tech'
  },
  {
    id: 9,
    firstName: 'Samantha',
    lastName: 'Dominic',
    description: 'Cat Lady!',
    email: 'msMeow@catlady.ca',
    password: 'floppyD',
    phone: '(647)715-2422',
    addressId: 9,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/55.jpg',
    skills: 'Animal care'
  },
  {
    id: 10,
    firstName: 'Jania',
    lastName: 'Pylowska',
    description: 'I am a real car nut: driving and doing basic repairs.',
    email: 'jania@greasemonkey.ca',
    password: 'iridium',
    phone: '(647)447-2422',
    addressId: 10,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/11.jpg',
    skills: 'Driving, mechanic.'
  },
  {
    id: 11,
    firstName: 'Morgan',
    lastName: "D'Angelo",
    description: 'I like troubleshooting technical problems, good with IT.',
    email: 'morgan.dangelo@utoronto.ca',
    password: '5Q$@Qkm3o%9t',
    phone: '(647)457-2988',
    addressId: 11,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/11.jpg',
    skills: 'Tech'
  },
  {
    id: 12,
    firstName: 'Dan',
    lastName: 'Jordan',
    description: 'I like helping seniors, I can drive you to appointments.',
    email: 'danny6000@gmail.com',
    password: '5Q$@o%9t',
    phone: '(647)744-2988',
    addressId: 12,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/45.jpg',
    skills: 'Driving, handyman'
  },
  {
    id: 13,
    firstName: 'Steve',
    lastName: 'Sakamoto',
    description: 'I like spending time outdoors, I can walk your dog.',
    email: 'steve@stevesakamoto.dev',
    password: '5Q$@ofhgkjhdfh%9t',
    phone: '(647)742-2911',
    addressId: 13,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/49.jpg',
    skills: 'Animal care, wordpress.'
  },
  {
    id: 14,
    firstName: 'Dominic',
    lastName: 'Peron',
    description: "I'm often driving around Toronto, I can pick things up and drop them off for you.",
    email: 'dom990@saultspring.ca',
    password: 'hdfh%9t',
    phone: '(647)744-7711',
    addressId: 14,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/55.jpg',
    skills: 'Driving, life-guard.'
  },
  {
    id: 15,
    firstName: 'Marcus',
    lastName: 'Knowles',
    description: 'DJ! Also love pet-sitting.',
    email: 'mizellbros@saultnoize.ca',
    password: 'hsdfghddfh%9t',
    phone: '(647)744-9991',
    addressId: 15,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/65.jpg',
    skills: 'DJ, animal care.'
  },
  {
    id: 16,
    firstName: 'Danny',
    lastName: 'Khan',
    description: 'Piano player, has BBQ skills',
    email: '88khan@theresariver.ca',
    password: 'hsdfght',
    phone: '(647)745-8921',
    addressId: 16,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/29.jpg',
    skills: 'Musician, cooking.'
  },
  {
    id: 17,
    firstName: 'John',
    lastName: 'DiGasperis',
    description: 'Woodworker and carpenter, I like to help seniors.',
    email: 'boostthatoyz@pierrefronds.ca',
    password: 'hsh%9t',
    phone: '(647)747-9955',
    addressId: 17,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/14.jpg',
    skills: 'Carpenter, house repairs.'
  },
  {
    id: 18,
    firstName: 'Samuel',
    lastName: 'Dormand',
    description: 'I like to go grocery shopping, and house-sitting.',
    email: 'dormand1237@gmail.com',
    password: 'hsh%9t',
    phone: '(647)788-9955',
    addressId: 18,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/male/39.jpg',
    skills: 'House-sitting, errands, yardwork.'
  },
  {
    id: 19,
    firstName: 'Anita',
    lastName: 'Silvers',
    description: 'I am a fiend for assembling Ikea furniture',
    email: 'silversart27@me.com',
    password: 'hsh%afsdkjh5879t',
    phone: '(647)847-9445',
    addressId: 19,
    stars: 0,
    avatar: 'https://xsgames.co/randomusers/assets/avatars/female/42.jpg',
    skills: 'Assembly, measurements, mounting and installation.'
  }
];

export { loggedInUser, allUsers };